version: "3.1"

services:
  # app:
  #   build: .
  #   volumes:
  #     - .:/app
  #   networks:
  #     - backend
  #   environment:
  #     PORT: 80
  #   ports:
  #     - "3001:80"
  #   command: bash -c 'npm install && node devServer.js'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - backend

networks:
  backend:
